// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrURqYvD63JWapksxR71OXthgL7Rb9Dcc',
    appId: '1:457007825339:android:c65a65731fb61c03c6849e',
    messagingSenderId: '457007825339',
    projectId: 'ar-chat-app-e7782',
    storageBucket: 'ar-chat-app-e7782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Y1GSSjx_SCIZGMV030Z-e0IlqLFjt1U',
    appId: '1:457007825339:ios:563629178af90f7ec6849e',
    messagingSenderId: '457007825339',
    projectId: 'ar-chat-app-e7782',
    storageBucket: 'ar-chat-app-e7782.appspot.com',
    iosBundleId: 'com.example.arChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwHGVsAJSoPRxny9TcTwQYkvykVkZieds',
    appId: '1:457007825339:web:4a037adfacca8b0ec6849e',
    messagingSenderId: '457007825339',
    projectId: 'ar-chat-app-e7782',
    authDomain: 'ar-chat-app-e7782.firebaseapp.com',
    storageBucket: 'ar-chat-app-e7782.appspot.com',
    measurementId: 'G-3Y36HG2QJP',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwHGVsAJSoPRxny9TcTwQYkvykVkZieds',
    appId: '1:457007825339:web:460546cf44757f4cc6849e',
    messagingSenderId: '457007825339',
    projectId: 'ar-chat-app-e7782',
    authDomain: 'ar-chat-app-e7782.firebaseapp.com',
    storageBucket: 'ar-chat-app-e7782.appspot.com',
    measurementId: 'G-B8WMMXVFY4',
  );

}